@echo off
echo Starting Backend Server...
cd "c:\Users\ccc\Documents\Github\ReactEcommerce\nodeEcomm"
echo Current directory: %cd%
echo Installing dependencies (if needed)...
npm install
echo Starting server...
npm start
pause
